name: Adds all Issues and Pull Requests to the project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@0.5.0
        with:
          project-url: https://github.com/users/ASpoonPlaysGames/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
